name: Caller Workflow
on:
  workflow_dispatch:
  
jobs:
  call_another_workflow:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Trigger Callee Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}  
          workflow: callee.yml
          ref: main