name: Callee Workflow
on:
  workflow_dispatch:

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Message
        run: echo "j1!"
  j2:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Message
        run: echo "j2!"
  jj:
    runs-on: ubuntu-latest
    needs: [j1, j2]
    steps:
      - name: Print a Message
        run: echo "jj!"
