name: Caller Workflow
on:
  workflow_dispatch:
  
jobs:
  call_another_workflow:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Trigger Target Workflow
        env:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $WORKFLOW_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/jzhang247/cs686-scratch/actions/workflows/callee/dispatches" \
            -d '{"ref":"main"}'
      - name: Trigger Callee Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          repository: ${{ github.repository }}
          workflow: callee.yml
          ref: main